<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml11-transitional.dtd">
<html>
	<head>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<title>SitRep</title>

		<link rel="stylesheet" href="/lib/srd_css/srd_style.css" type="text/css" />
		<link rel="stylesheet" href="/lib/srd_css/srd_view_style.css" type="text/css" />


				<!--.olControlPanel  DESCRIBES THE PANEL ITSELF -->
				<!-- olControlPanel div  DESCRIBES THE ELE IN THE PANEL (DEFAULTS) -->
		<style type="text/css">
            html, body  {
                border: 0; padding: 0; margin: 0;
                width: 612px;
                height: 100%;
								background-color:white;
			      }

						#theSrdDoc { 
								min-height: 100%;
                width: 100%;
                height: auto !important;
                height: 100%;
			      }
	
						
		</style>	


		<script type="text/javascript" data-dojo-config="async: true" src="/lib/dojo/dojo.js"></script>

		<script type="text/javascript">

		dojoConfig = {
			baseUrl: "lib",
			tlmSiblingOfDojo: false,
			packages: [
				{ name: "dojo", location: "dojo" },
				{ name: "dijit", location: "dijit" },
				{ name: "dojox", location: "dojox" },
				{ name: "srd_js", location: "srd_js" }
			]
		};
		loadsrd = {};


		require([
//			"dojo/dom",
//			"dijit/registry",
//			"dojo/parser",
//			"dojo/_base/declare",
//			"dojox/layout/GridContainer",
//			"dijit/form/Form",
//			"srd_js/srd_gridContainer",
//			"srd_js/srd_editPalette",
//			"srd_js/srd_layer",
//			"srd_js/srd_view",
//			"srd_js/srd_view_opstrack",
//			"srd_js/srd_view_map",
//			"srd_js/srd_view_datagrid",
//			"srd_js/srd_view_admin",
			"srd_js/srd_view_cfssingle",
//			"srd_js/srd_document",
			"dijit/layout/LayoutContainer",
			"dojo/domReady!"

		], function( srd_view_cfssingle ) {

				var parArr = dojo.queryToObject(location.search.substr(1) );
				var theCon = new dijit.layout.LayoutContainer( {
					style:'overflow:auto'
				}, 'theSrdDoc');
				var theDoc = { 'viewContainer': theCon};
<?php
       echo "theDoc.siteLeftImage='".$this->srd_login_opts['leftimage']."';\n";
       echo "theDoc.siteRightImage='".$this->srd_login_opts['rightimage']."';\n";
       echo "theDoc.siteTitle='".$this->srd_login_opts['title']."';\n";
?>
				var data = {xDim:1, yDim:1, noContainers:true};
				var theView = new srd_view_cfssingle(data, theDoc);	
//				console.log("TEST:::"+parArr.cfs_date+":::"+parArr.cfs_num);
				if(parArr) {
					theView.getJob(parArr.cfs_date, parArr.cfs_num);
				}
			} );


		</script>
</head>

 	<body class="tundra" >
		<div id="theSrdDoc"  >
		</div>
	</body>
</html>
