	<head>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<title>SitRep</title>

		<link rel="stylesheet" href="lib/SR_Dojo/dijit/themes/tundra/tundra.css" type="text/css" />
		<link rel="stylesheet" href="lib/SR_Dojo/dojox/layout/resources/ExpandoPane.css" type="text/css" />
		<link rel="stylesheet" href="lib/SR_Dojo/dojox/layout/resources/GridContainer.css" type="text/css" />
		<link rel="stylesheet" href="lib/SR_Dojo/dojox/layout/resources/DndGridContainer.css" type="text/css" />
		<link rel="stylesheet" href="lib/SR_Dojo/srd/form.css" type="text/css" />
		<link rel="stylesheet" href="lib/SR_Dojo/srd/srd_style.css" type="text/css" />

		<link rel="stylesheet" href="lib/SR_OpenLayers/theme/default/style.css" type="text/css" />

				<!--.olControlPanel  DESCRIBES THE PANEL ITSELF -->
				<!-- olControlPanel div  DESCRIBES THE ELE IN THE PANEL (DEFAULTS) -->
		<style type="text/css">
            html, body  {
                border: 0; padding: 0; margin: 0;
                width: 100%;
                height: 100%;
			      }
						#theSrdDoc, #srd_container { 
                width: 100%;
                height: 100%;
			      }
						
						.srd_view_label {
							background-color:lightgrey;
							padding-left: 5px;
						}
	
            #text {
                position: absolute;
                bottom: 1em;
                left: 1em;
                width: 512px;
                z-index: 20000;
                background-color: white;
            }

						.dojoxExpandoClosed .dojoxExpandoTitleNode {
							display:inline;
						}
			
						.gridContainerZone {
							margin: 0px;
						}

		</style>	

		<script type="text/javascript" src="lib/SR_Dojo/dojo/dojo.js" ></script>
		<script type="text/javascript" src="lib/SR_Dojo/dojo/srd_dojo.js" ></script>

		<script src="lib/SR_OpenLayers/OpenLayers.js"></script>

		<script src="lib/srd_js/srd_gridContainer.js"></script>
		<script src="lib/srd_js/srd_editPalette.js"></script>
		<script src="lib/srd_js/srd_layer.js"></script>
		<script src="lib/srd_js/srd_view.js"></script>
		<script src="lib/srd_js/srd_view_map.js"></script>
		<script src="lib/srd_js/srd_view_datagrid.js"></script>
		<script src="lib/srd_js/srd_view_admin.js"></script>
		<script src="lib/srd_js/srd_edit.js"></script>
		<script src="lib/srd_js/srd_document.js"></script>

		<script type="text/javascript">
			var srd = new srd_document();	
		</script>
	</head>


