<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml11-transitional.dtd">
<html>
	<head>
		<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<title>SitRep</title>

		<link rel="stylesheet" href="lib/dijit/themes/tundra/tundra.css" type="text/css" />

		<link rel="stylesheet" href="lib/dojox/layout/resources/ExpandoPane.css" type="text/css" />
		<link rel="stylesheet" href="lib/dojox/layout/resources/GridContainer.css" type="text/css" />
		<link rel="stylesheet" href="lib/dojox/layout/resources/DndGridContainer.css" type="text/css" />
		<link rel="stylesheet" href="lib/dojox/grid/enhanced/resources/tundra/EnhancedGrid.css" type="text/css" />
		<link rel="stylesheet" href="lib/dojox/grid/enhanced/resources/EnhancedGrid_rtl.css" type="text/css" />
		<link rel="stylesheet" href="lib/srd/css/form.css" type="text/css" />

		<link rel="stylesheet" href="lib/srd/css/srd_style.css" type="text/css" />
		<link rel="stylesheet" href="lib/srd/css/srd_view_style.css" type="text/css" />


		<link rel="stylesheet" href="lib/OpenLayers/theme/default/style.css" type="text/css" />

				<!--.olControlPanel  DESCRIBES THE PANEL ITSELF -->
				<!-- olControlPanel div  DESCRIBES THE ELE IN THE PANEL (DEFAULTS) -->
		<style type="text/css">
            html, body  {
                border: 0; padding: 0; margin: 0;
                width: 100%;
                height: 100%;
			      }
						#theSrdDoc { 
								min-height: 100%;
                width: 100%;
                height: auto !important;
								height: 100%;
								overflow: visible;
			      }

						#srd_container { 
                width: 100%;
								height: 100%;
						
			      }
	

						
						.srd_view_label {
							background-color:lightgrey;
							padding-left: 5px;
						}
	
            #text {
                position: absolute;
                bottom: 1em;
                left: 1em;
                width: 512px;
                z-index: 20000;
                background-color: white;
            }

						.dojoxExpandoClosed .dojoxExpandoTitleNode {
							display:inline;
						}
			
						.gridContainerZone {
							margin: 0px;
						}

		</style>	
		
		<link rel="stylesheet" type="text/css" href="lib/srd/css/SitRep_Dark.css" />


		<script src="lib/OpenLayers/OpenLayers.js"></script>
		<script type="text/javascript" >

		dojoConfig = {
			baseUrl: "lib",
			tlmSiblingOfDojo: true,
			packages: [
				{ name: "dojo", location: "dojo" },
				{ name: "dijit", location: "dijit" },
				{ name: "dojox", location: "dojox" },
				{ name: "srd", location: "srd" },
				{ name: "org", location: "org" }
			]
		};
		</script>


		<script data-dojo-config="async: 1 " src="lib/dojo/dojo.js" ></script>
		<script data-dojo-config="async: 0" src="lib/srd/doc_include.js" ></script>
		<script data-dojo-config="async: 0" src="lib/srd/view_include.js" ></script>

		<script>
		loadsrd = {};
		require([
			"srd/srd_document",
			"dojo/domReady!"
		], function( srd_document ) {

				srd = new srd_document();
				srd.srd_init();
<!--
<?php
       echo "loadsrd.siteLeftImage='".$this->srd_login_opts['leftimage']."';\n";
       echo "loadsrd.siteRightImage='".$this->srd_login_opts['rightimage']."';\n";
       echo "loadsrd.siteTitle='".$this->srd_login_opts['title']."';\n";
?>
-->
		} );

		</script>


