	</script>
		<style>
			@import "lib/srd/css/srd.css";
			@import "lib/OpenLayers/theme/default/style.css";
		</style>

		<script type="text/javascript" >

		dojoConfig = {
			baseUrl: "lib",
			tlmSiblingOfDojo: true,
			packages: [
				{ name: "dojo", location: "dojo" },
				{ name: "dijit", location: "dijit" },
				{ name: "dojox", location: "dojox" },
				{ name: "srd", location: "srd" },
				{ name: "org", location: "org" }
			]
		};

		</script>
<!--
		<script data-dojo-config="async: 0" src="lib/srd/dojo_bootloader.js" ></script>
		<script data-dojo-config="async: 0" src="lib/srd/include_view.js" ></script>
-->
		<script data-dojo-config="async: 1 " src="lib/dojo/dojo.js" ></script>
		<script src="lib/OpenLayers/OpenLayers.js"></script>

		<script>
		require([
			"srd/srd_document",
			"dojo/domReady!"
		], function( srd_document ) {

				srd = srd_document(loadsrd);
				srd.srd_init();
		} );

		</script>


