
		<script type="text/javascript" >

		dojoConfig = {
			baseUrl: "lib",
			tlmSiblingOfDojo: true,
			packages: [
				{ name: "dojo", location: "dojo" },
				{ name: "dijit", location: "dijit" },
				{ name: "dojox", location: "dojox" },
				{ name: "srd", location: "srd" },
				{ name: "org", location: "org" }
			]
		};

			OpenLayers = parent.OpenLayers;
			require = parent.require;
			define = parent.define;		
			dojo = parent.dojo;
			dojox = parent.dojox;
	
		</script>

		<script data-dojo-config="async: 0" src="../../lib/dojo/dojo.js" ></script>
		<script data-dojo-config="async: 0" src="../../lib/srd/include_view.js" ></script>

		<script>
		loadsrd = {};
		require( {
			baseUrl: window.location.protocol + "//" + window.location.host + '/lib',
			packages : [
				{ name: "dojo", location: "dojo" },
				{ name: "dijit", location: "dijit" },
				{ name: "dojox", location: "dojox" },
				{ name: "srd", location: 'srd' },
				{ name: "org", location: "org" }
			]
		}, [
			"srd/srd_document",
			"dojo/domReady!"
		], function( srd_document ) {

				srd = new srd_document();
				srd.srd_init();
<!--
<?php
       echo "loadsrd.siteLeftImage='".$this->srd_login_opts['leftimage']."';\n";
       echo "loadsrd.siteRightImage='".$this->srd_login_opts['rightimage']."';\n";
       echo "loadsrd.siteTitle='".$this->srd_login_opts['title']."';\n";
?>
-->
		} );

		</script>


