<html>
	<head>
		<title>SitRep Login Page</title>
		<link rel="stylesheet" href="lib/SR_Dojo/srd/srd_style.css" type="text/css" />
		<script type="text/javascript" src="lib/SR_Dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
		<script type="text/javascript" src="lib/SR_Dojo/dojo/srd_dojo.js" djConfig="parseOnLoad: true"></script>

    <script type="text/javascript" djConfig="parseOnLoad: true" >
			dojo.require("dijit.Dialog");
			dojo.require("dijit.layout.ContentPane");
			function srd_login() {
				dojo.addOnLoad(function () {
					dijit.byId('loginDialog').show();
				} );
			}
			
		</script>
	</head>
	<body class="tundra" onload="srd_login()">

<?php

?>
		<div id="loginDialog"  dojoType="dijit.Dialog" closable=false style="margin:0px;">
			<div dojoType="dijit.layout.BorderContainer"  style="background:grey;width:400px;height:350px;padding:10px;margin:0px;border:0px;" gutters=false >
				<div dojoType="dijit.layout.ContentPane" style="width:20%;" region="left" ></div>
				<div dojoType="dijit.layout.ContentPane" style="width:20%;background:grey;" region="right" ></div>
				<div dojoType="dijit.layout.ContentPane" style="height:20%;" region="top" >
					<img src="/lib/img/NYPD_Shield_Alpha2.png" style="width:50px;height:50px;float:left" />
					<img src="/lib/img/NYPD_Seal_Alpha2.png" style="width:50px;height:50px;float:right;"/>
				
				</div>
				<div dojoType="dijit.layout.ContentPane" title="Login" style="background:grey;width:200;height:50;padding:0px" region="center">
				<h1>SitRep Login:</h1>
<?php
	if(!empty($this->message) ) {
		echo '<font color="red">';
		echo $this->escape($this->message[0]);
		echo '</font>';
	}
	$this->form->setName('login')
						 ->setAction('/login/index/login')
						 ->setMethod('post');
	echo $this->form;
?>


				</div>
				<div dojoType="dijit.layout.ContentPane" style="height:20%;" region="bottom" >
					<br>
					<img src="/lib/img/SitRepLogo_Tiny.png" style="width:100px;height:50px;float:left" />
					<img src="/lib/img/OSrce_Alpha1.png" style="width:100px;height:50px;float:right;"/>
				</div>
			</div>
		</div>


	</body>
</html>
